name: CICD GITHUB ACTION SPRING BOOT
description: This is project to learn setting up CICD pipeline as a DevOps Engr using GITHUB ACTION

on: 
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    name: build and deploy spring boot app
    runs-on: ubuntu-latest
    steps:
      # checking out the code from github
      - name: Checkout the Code
        uses: actions/checkout@v4

      # install java to our system
      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with: 
          distribution: 'corretto'
          java-version: 17
      
      # running test on the app
      - name: Running Unit test
        run: mvn -B test --file pom.xml

      # building th java app
      - name: Build app
        run: |
          mvn clean
          mvn -B package --file pom.xml

      # building the docker image
      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ secrets.DOCKET_HUB_USERNAME }}/spring-boot-cicd-demo/today

      # login into docker Hub
      - name: Docker authentication
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKET_HUB_USERNAME }}
          password: ${{ secrets.DOCKET_HUB_ACCESS_TOKEN }}

      # build and push image to docker Hub
      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKET_HUB_USERNAME }}/spring-boot-cicd-demo/today



